#!/bin/bash

xrandr --orientation left
xinput set-prop "ILITEK Multi-Touch-V" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1

# Import variables
. /home/kiosk/.kiosk/browser.cfg

# Uncomment to run touchscreen calibration on next boot
#xterm xinput_calibrator

# Disable right-click
if [ $nocontextmenu != "False" ]
	then xmodmap -e "pointer = 1 2 99"
fi

xset s off # Disable screensaver
xset -dpms # Disable DPMS (Energy Star) features
xset s noblank # Do not blank the screen
	
# Start window manager
matchbox-window-manager -use_titlebar no &

# Relaunch browser if closed
while true; do
	export DISPLAY=:0
	chromium-browser --kiosk --disable-infobars --noerrdialogs --disable-session-crashed-bubble --disable-pinch --enable-remote-extensions --disable-save-password-bubble --touch-events=enabled --disable-gesture-typing --overscroll-history-navigation=0 --disable-translate --agc-startup-min-volume=100 $home_url
	sleep 5s
done

